export default {
    secretKey: process.env.SECRET_KEY_SERVER || '',
    host: 'http://localhost',
    port: process.env.PORT || '',
    deviceName: 'WppConnect',
    poweredBy: 'WPPConnect-Server',
    startAllSession: true,
    tokenStoreType: 'mongodb', // Altere de 'file' para 'mongodb'
    maxListeners: 15,
    customUserDataDir: './userDataDir/',
    webhook: {
      url: null,
      autoDownload: true,
      readMessage: true,
      allUnreadOnStart: false,
      listenAcks: true,
      onPresenceChanged: true,
      onParticipantsChanged: true,
      onReactionMessage: true,
      onPollResponse: true,
      onRevokedMessage: true,
      onLabelUpdated: true,
      onSelfMessage: false,
    },
    chatwoot: {
      sendQrCode: true,
      sendStatus: true,
    },
    archive: {
      enable: false,
      waitTime: 10,
      daysToArchive: 45,
    },
    log: {
      level: 'silly', // Before opening an issue, change the level to silly and retry an action
      logger: ['console', 'file'],
    },
    createOptions: {
      browserArgs: [
        '--disable-web-security',
        '--no-sandbox',
        '--disable-web-security',
        '--aggressive-cache-discard',
        '--disable-cache',
        '--disable-application-cache',
        '--disable-offline-load-stale-cache',
        '--disk-cache-size=0',
        '--disable-background-networking',
        '--disable-default-apps',
        '--disable-extensions',
        '--disable-sync',
        '--disable-translate',
        '--hide-scrollbars',
        '--metrics-recording-only',
        '--mute-audio',
        '--no-first-run',
        '--safebrowsing-disable-auto-update',
        '--ignore-certificate-errors',
        '--ignore-ssl-errors',
        '--ignore-certificate-errors-spki-list',
      ],
    },
    mapper: {
      enable: false,
      prefix: 'tagone-',
    },
    db: {
      mongodbDatabase: 'tokens',
      mongodbCollection: '',
      mongodbUser: process.env.MONGODB_USER || '',
      mongodbPassword: process.env.MONGODB_PASSWORD || '',
      mongodbHost: process.env.MONGODB_HOST || '',
      mongoIsRemote: false,
      mongoURLRemote: '',
      mongodbPort: 27017,
      redisHost: process.env.REDIS_HOST || 'localhost',
      redisPort: process.env.REDIS_PORT || 6379,
      redisPassword: process.env.REDIS_PASSWORD || '',
      redisDb: 0,
      redisPrefix: 'docker',
    },
  };
  